In [11]:
from PIL import Image
from glob import glob

files = ["./sample_data/{}.png".format(i) for i in range(24)]
im0 = files[:12]
im1 = files[12:]
im0

['./sample_data/0.png',
 './sample_data/1.png',
 './sample_data/2.png',
 './sample_data/3.png',
 './sample_data/4.png',
 './sample_data/5.png',
 './sample_data/6.png',
 './sample_data/7.png',
 './sample_data/8.png',
 './sample_data/9.png',
 './sample_data/10.png',
 './sample_data/11.png']

In [14]:
for i in range(12,24):
    img = Image.open("./sample_data/{}.png".format(i))
    img.save("./sample_data/{}.png".format(i+24))

In [1]:
from dataloader.dataset import Dataset

train = Dataset("train")

In [2]:
i = 0
x = train[i]["input"]
y = train[i]["label"]


In [6]:

def show_tensor(x):
    for i in x[2].numpy():
        text = ""
        for k in i:
            text += str(int(k)) + " "
        print(text)
show_tensor(x)
print(y)

0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1

In [25]:
train.y

array([0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1])

In [17]:
import numpy as np
from PIL import Image
a = np.array([[1,2,3,4],[2,3,4,5],[3,4,5,6],[4,5,6,7]])
print(a)
img = Image.fromarray(np.uint8(a))
img = np.asarray(img.resize((2, 2)))
print(img)

[[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]]
[[3 5]
 [5 7]]


In [5]:
train[0]["input"]

tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]])

In [3]:
for i in range(5):
    print(i)

0
1
2
3
4


In [4]:
i

4

In [2]:
b = AAA(5)
b

TypeError: __init__() should return None, not 'int'

In [40]:
b.run()

5

In [13]:
!pwd

/home/kataoka/desktop/proj/pytorch-template


# はじめに

このjupyterファイルはtrainerなどの開発を行うために使用します。

# Train()

## tqdm_notebook

### tqdm installation

`pip install tqdm`  
`jupyter nbextension enable --py --sys-prefix widgetsnbextension`  
`jupyter labextension install @jupyter-widgets/jupyterlab-manager`

In [22]:
from tqdm import tqdm_notebook as tqdm
from tqdm import tnrange
from time import sleep

hoge = [i for i in range(5)]
for i in tqdm(hoge, desc=' '):
    for k in tqdm(range(10), desc='Model', leave=False):
        sleep(0.1)

In [1]:
from train import Train

Train()

ImportError: cannot import name 'Train' from 'train' (/mnt/c/Users/kataoka/Desktop/proj/pytorch-template/train.py)