In [1]:
from metrics import Evaluator

num_class = 2

evl = Evaluator(num_class)
print(evl.num_class)

2


In [2]:
import numpy as np
gt = np.array([[0,0,0,1,1],[1,1,1,1,1]])
pr = np.array([[1,1,1,1,1],[1,1,1,1,1]])

print(gt)
print(pr)

[[0 0 0 1 1]
 [1 1 1 1 1]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


In [3]:
evl.__init__(num_class)
print(evl.confusion_matrix)
evl.add_batch(gt, pr)
print()
print(evl.confusion_matrix)

[[0. 0.]
 [0. 0.]]

[[0. 3.]
 [0. 7.]]


In [4]:
evl.confusion_matrix.sum(axis=1)

array([3., 7.])

In [5]:
print(evl.Precision())

[0.  0.7]


/mnt/c/Users/Shotaro Kataoka/Desktop/github/pytorch-template/utils/metrics.py:26: RuntimeWarning: invalid value encountered in true_divide
  Precision = np.diag(self.confusion_matrix) / self.confusion_matrix.sum(axis=0)


In [6]:
print(evl.Recall())

[0. 1.]


In [7]:
print(evl.F_score())

[0.         0.82352941]


/mnt/c/Users/Shotaro Kataoka/Desktop/github/pytorch-template/utils/metrics.py:33: RuntimeWarning: invalid value encountered in true_divide
  F_score = 2 * Recall * Precision / (Recall + Precision)
